const ASM_QUESTIONS = [
  // ===================== CHAPITRE 1 - NUMERATION & LOGIQUE (15) =====================
  {id:1, ch:1, q:"La base du binaire est :", o:["2","8","10","16"], a:0, e:"Le binaire est en base 2."},
  {id:2, ch:1, q:"L'hexadecimal utilise :", o:["0-7","0-9","0-9 et A-F","A-Z"], a:2, e:"Hexa = 0-9 et A-F."},
  {id:3, ch:1, q:"Le groupement binaire pour l'hexa est :", o:["2 bits","3 bits","4 bits","8 bits"], a:2, e:"Hexa = groupes de 4 bits."},
  {id:4, ch:1, q:"11010110b vaut en hexa :", o:["D6","C6","D3","E6"], a:0, e:"1101 0110 = D6."},
  {id:5, ch:1, q:"25 decimal vaut en binaire :", o:["11001","11100","10011","10110"], a:0, e:"25 = 16 + 8 + 1 = 11001."},
  {id:6, ch:1, q:"Complement a 2 =", o:["Inverser seulement","Inverser puis +1","Ajouter 2","Multiplier par -1"], a:1, e:"Complement a 2 = inversion + 1."},
  {id:7, ch:1, q:"Plage signee sur 8 bits :", o:["0..255","-128..127","-127..128","-255..255"], a:1, e:"Signe 8 bits = -128..127."},
  {id:8, ch:1, q:"Plage non signee sur 8 bits :", o:["0..255","-128..127","-127..128","0..127"], a:0, e:"Non signe 8 bits = 0..255."},
  {id:9, ch:1, q:"-13 en complement a 2 (8 bits) :", o:["11110011","11101101","10001101","00001101"], a:0, e:"13=00001101, inverse=11110010, +1=11110011."},
  {id:10, ch:1, q:"AND sert surtout a :", o:["Forcer a 1","Garder certains bits","Diviser","Inverser"], a:1, e:"AND conserve les bits du masque."},
  {id:11, ch:1, q:"OR sert surtout a :", o:["Garder","Forcer a 1","Tester","Inverser"], a:1, e:"OR force les bits a 1."},
  {id:12, ch:1, q:"XOR sert surtout a :", o:["Basculer des bits","Diviser","Ajouter","Masquer"], a:0, e:"XOR inverse les bits du masque."},
  {id:13, ch:1, q:"Tester un bit k se fait avec :", o:["x | (1<<k)","x & (1<<k)","x ^ (1<<k)","x + (1<<k)"], a:1, e:"AND avec un masque a 1 sur k."},
  {id:14, ch:1, q:"Decalage gauche par 1 equivaut a :", o:["/2","*2","+1","-1"], a:1, e:"Shift left = x2 (sans depassement)."},
  {id:15, ch:1, q:"Decalage droite arithmetique :", o:["Met 0","Preserve le signe","Inverse","Ajoute 1"], a:1, e:"Il replique le bit de signe."},

  // ===================== CHAPITRE 2 - CPU & CYCLE (15) =====================
  {id:16, ch:2, q:"Ordre classique du cycle :", o:["Decode-Fetch-Execute","Fetch-Decode-Execute-Writeback","Execute-Decode-Fetch","Fetch-Execute-Decode"], a:1, e:"Cycle standard: fetch, decode, execute, write-back."},
  {id:17, ch:2, q:"L'ALU sert a :", o:["Stocker","Calculer","Gerer le bus","Synchroniser"], a:1, e:"ALU = operations arithmetiques et logiques."},
  {id:18, ch:2, q:"Le composant le plus rapide est :", o:["RAM","Cache","Registres","SSD"], a:2, e:"Les registres sont les plus rapides."},
  {id:19, ch:2, q:"Le bus d'adresses transporte :", o:["Des adresses","Des donnees","Des flags","Du code"], a:0, e:"Il indique ou lire/ecrire."},
  {id:20, ch:2, q:"Le bus de donnees transporte :", o:["Des adresses","Des donnees","Des flags","Des interruptions"], a:1, e:"Il transporte les valeurs lues/ecrites."},
  {id:21, ch:2, q:"Le cache sert surtout a :", o:["Remplacer RAM","Eviter des acces RAM lents","Stocker le programme","Gerer IRQ"], a:1, e:"Le cache reduit la latence memoire."},
  {id:22, ch:2, q:"Zero flag (Z) est a 1 quand :", o:["Resultat nul","Resultat negatif","Carry actif","Overflow actif"], a:0, e:"Z=1 si resultat = 0."},
  {id:23, ch:2, q:"Carry indique :", o:["Overflow signe","Overflow non signe","Erreur memoire","Reset"], a:1, e:"Carry = depassement en non signe."},
  {id:24, ch:2, q:"Overflow (V) indique :", o:["Non signe","Signe","Cache plein","IRQ"], a:1, e:"Overflow concerne les calculs signes."},
  {id:25, ch:2, q:"Une interruption :", o:["Arrete le CPU","Detourne vers une ISR","Efface la RAM","Change l'horloge"], a:1, e:"Le CPU saute vers l'ISR puis revient."},
  {id:26, ch:2, q:"Le pointeur d'instruction x64 est :", o:["RSP","RIP","RAX","RDI"], a:1, e:"RIP pointe l'instruction courante."},
  {id:27, ch:2, q:"Hierarchie du plus rapide au plus lent :", o:["RAM-Cache-Registres-Disque","Registres-Cache-RAM-Disque","Cache-RAM-Registres-Disque","Registres-RAM-Cache-Disque"], a:1, e:"Registres > cache > RAM > disque."},
  {id:28, ch:2, q:"Write-back sert a :", o:["Lire opcode","Ecrire resultat","Changer bus","Declencher IRQ"], a:1, e:"Write-back ecrit le resultat."},
  {id:29, ch:2, q:"Une machine a etats CPU decrit :", o:["Un disque","Des etapes d'execution","Un socket","Un bus"], a:1, e:"Le CPU passe par des etats fixes."},
  {id:30, ch:2, q:"Opcode signifie :", o:["Valeur des donnees","Code d'operation","Adresse RAM","Nom de variable"], a:1, e:"L'opcode est le code de l'instruction."},

  // ===================== CHAPITRE 3 - AVR & ATmega (15) =====================
  {id:31, ch:3, q:"Un microcontroleur integre :", o:["CPU seul","CPU + memoires + peripheriques","RAM seule","GPU"], a:1, e:"Microcontroleur = tout en un."},
  {id:32, ch:3, q:"L'architecture AVR est :", o:["Von Neumann","Harvard","CISC","GPU"], a:1, e:"AVR = Harvard (code/donnees separes)."},
  {id:33, ch:3, q:"La Flash contient :", o:["Le programme","La pile","Les flags","Le cache"], a:0, e:"Flash = code."},
  {id:34, ch:3, q:"La SRAM contient :", o:["Variables et stack","Programme","EEPROM","Cache"], a:0, e:"SRAM = donnees volatiles."},
  {id:35, ch:3, q:"EEPROM est :", o:["Volatile","Persistante","Cache","Pile"], a:1, e:"EEPROM conserve les donnees."},
  {id:36, ch:3, q:"DDR sert a :", o:["Direction des broches","Activer timer","Reset","Mesurer tension"], a:0, e:"DDR fixe entree/sortie."},
  {id:37, ch:3, q:"PORT en mode entree sert a :", o:["Activer pull-up","Effacer Flash","Reset","Changer horloge"], a:0, e:"PORT=1 active un pull-up."},
  {id:38, ch:3, q:"PIN sert a :", o:["Lire l'etat","Ecrire","Compiler","Debugger"], a:0, e:"PIN lit l'etat des broches."},
  {id:39, ch:3, q:"SEI sert a :", o:["Desactiver IRQ","Activer IRQ","Reset","NOP"], a:1, e:"SEI active les interruptions."},
  {id:40, ch:3, q:"RETI sert a :", o:["Retour ISR","Reset","NOP","CALL"], a:0, e:"RETI revient d'une interruption."},
  {id:41, ch:3, q:"Un timer sert a :", o:["Compter le temps","Changer l'ALU","Effacer RAM","Modifier le bus"], a:0, e:"Timer = compteur + IRQ."},
  {id:42, ch:3, q:"Prescaler sert a :", o:["Diviser l'horloge","Ajouter RAM","Changer Flash","Reset"], a:0, e:"Prescaler ralentit le timer."},
  {id:43, ch:3, q:"UART est un bus :", o:["Serie","Parallele","Optique","I2C uniquement"], a:0, e:"UART est un protocole serie."},
  {id:44, ch:3, q:"ADC sert a :", o:["Convertir analogique en numerique","Compter IRQ","Stocker code","Mesurer bits"], a:0, e:"ADC = Analog to Digital Converter."},
  {id:45, ch:3, q:"Ecrire 1 dans PINx peut :", o:["Toggler la sortie","Effacer Flash","Reset","Desactiver UART"], a:0, e:"Sur AVR, PINx peut toggler la broche."},

  // ===================== CHAPITRE 4 - TOOLCHAIN (10) =====================
  {id:46, ch:4, q:"Compilation croisee =", o:["Compiler et executer sur PC","Compiler pour une autre cible","Compiler sans outil","Compiler en binaire"], a:1, e:"On compile pour une cible differente."},
  {id:47, ch:4, q:"Le fichier .o est :", o:["Objet intermediaire","Binaire final","Image flashable","Script"], a:0, e:".o = objet intermediaire."},
  {id:48, ch:4, q:"Le fichier .elf est :", o:["Binaire lie","Fichier texte","Audio","Image"], a:0, e:".elf = binaire lie."},
  {id:49, ch:4, q:"Le fichier .hex sert a :", o:["Programmer la Flash","Stocker logs","Changer RAM","Decrire ports"], a:0, e:".hex est flashe sur la carte."},
  {id:50, ch:4, q:"avr-objcopy permet :", o:["Compiler","Convertir ELF->HEX","Flasher","Emuler"], a:1, e:"Il convertit le binaire."},
  {id:51, ch:4, q:"avrdude sert a :", o:["Flasher","Compiler","Editer","Emuler"], a:0, e:"avrdude charge le firmware."},
  {id:52, ch:4, q:"L'option qui cible la puce :", o:["-mmcu=atmega328p","-O2","-Wall","-g"], a:0, e:"-mmcu selectionne le MCU."},
  {id:53, ch:4, q:"Ordre logique :", o:["HEX->ELF->O","O->ELF->HEX->Flash","ELF->O->HEX","Flash->HEX"], a:1, e:"Objet puis ELF, puis HEX, puis flash."},
  {id:54, ch:4, q:"LED blink necessite :", o:["DDR en sortie","DDR en entree","EEPROM","Cache"], a:0, e:"La broche doit etre en sortie."},
  {id:55, ch:4, q:"Un echec de flash vient souvent de :", o:["Mauvais port/MCU","RAM trop grande","Cache vide","RAX"], a:0, e:"MCU, programmeur et port doivent correspondre."},

  // ===================== CHAPITRE 5 - AVR ASM (15) =====================
  {id:56, ch:5, q:"LDI charge :", o:["Une adresse","Une valeur immediate","Un flag","Un port"], a:1, e:"LDI charge une constante."},
  {id:57, ch:5, q:"LDI fonctionne sur :", o:["R0-R15","R16-R31","Tous les registres","R0 seulement"], a:1, e:"LDI cible R16-R31."},
  {id:58, ch:5, q:"IN/OUT servent a :", o:["Acceder aux registres E/S","Lire la Flash","Changer la pile","Reset"], a:0, e:"IN/OUT = espace E/S."},
  {id:59, ch:5, q:"LDS/STS servent a :", o:["Acceder a la SRAM","Acceder aux ports","Acceder a la Flash","Changer le cache"], a:0, e:"LDS/STS lisent/ecrivent en SRAM."},
  {id:60, ch:5, q:"SREG contient :", o:["Les flags","Le programme","La pile","La Flash"], a:0, e:"SREG = status register."},
  {id:61, ch:5, q:"Pointeur X =", o:["R27:R26","R31:R30","R29:R28","R25:R24"], a:0, e:"X = R27:R26."},
  {id:62, ch:5, q:"Pointeur Z =", o:["R31:R30","R29:R28","R27:R26","R25:R24"], a:0, e:"Z = R31:R30."},
  {id:63, ch:5, q:"CP/CPI servent a :", o:["Comparer et mettre les flags","Charger une constante","Sauter","Reset"], a:0, e:"CP/CPI mettent a jour Z, C, N..."},
  {id:64, ch:5, q:"BREQ saute si :", o:["Z=1","Z=0","C=1","V=1"], a:0, e:"BREQ = branch if equal."},
  {id:65, ch:5, q:"BRNE saute si :", o:["Z=1","Z=0","C=1","V=1"], a:1, e:"BRNE = branch if not equal."},
  {id:66, ch:5, q:"RJMP est :", o:["Un saut relatif","Un saut absolu","Un reset","Un test"], a:0, e:"RJMP saute relativement."},
  {id:67, ch:5, q:"SEI sert a :", o:["Activer IRQ","Desactiver IRQ","NOP","Reset"], a:0, e:"SEI active les interruptions."},
  {id:68, ch:5, q:"La pile AVR :", o:["Monte","Descend (SP diminue)","Inchange","Est en Flash"], a:1, e:"SP diminue quand on push."},
  {id:69, ch:5, q:"Avant CALL/INT, on doit :", o:["Init stack","Effacer DDR","Reset","Changer Flash"], a:0, e:"La pile doit etre initialisee."},
  {id:70, ch:5, q:"Pour effacer un bit :", o:["OR","AND avec masque 0","XOR","ADD"], a:1, e:"AND avec un masque a 0 sur le bit cible."},

  // ===================== CHAPITRE 6 - NASM BASES (15) =====================
  {id:71, ch:6, q:"Section .text =", o:["Code","Donnees","Pile","Cache"], a:0, e:".text contient les instructions."},
  {id:72, ch:6, q:"Section .data =", o:["Donnees initialisees","Donnees non init","Code","Pile"], a:0, e:".data contient des donnees initialisees."},
  {id:73, ch:6, q:"Section .bss =", o:["Donnees non initialisees","Code","Pile","Flags"], a:0, e:".bss reserve la memoire."},
  {id:74, ch:6, q:"db correspond a :", o:["1 octet","2 octets","4 octets","8 octets"], a:0, e:"db = byte."},
  {id:75, ch:6, q:"dq correspond a :", o:["1 octet","2 octets","4 octets","8 octets"], a:3, e:"dq = qword."},
  {id:76, ch:6, q:"RAX est :", o:["16 bits","32 bits","64 bits","8 bits"], a:2, e:"RAX est 64 bits."},
  {id:77, ch:6, q:"EAX est :", o:["Bas 32 bits de RAX","Haut 32 bits","Registre AVR","Adresse"], a:0, e:"EAX = partie 32 bits."},
  {id:78, ch:6, q:"[rbx] signifie :", o:["Valeur immediate","Adresse memoire","Label","Opcode"], a:1, e:"Crochets = dereferencement memoire."},
  {id:79, ch:6, q:"MOV RAX, [var] fait :", o:["Charge l'adresse","Charge la valeur","Ecrit en memoire","Ignore"], a:1, e:"MOV lit la valeur en memoire."},
  {id:80, ch:6, q:"LEA sert a :", o:["Calculer une adresse","Lire memoire","Ecrire memoire","Changer RSP"], a:0, e:"LEA calcule l'adresse."},
  {id:81, ch:6, q:"Adressage base+index*scale :", o:["[rbx+rcx*4]","[rbx-]","[rip]","[rax+rax]"], a:0, e:"Index * scale est possible en x86_64."},
  {id:82, ch:6, q:"RSP est :", o:["Stack pointer","Instruction pointer","Data pointer","Flag"], a:0, e:"RSP pointe la pile."},
  {id:83, ch:6, q:"RIP contient :", o:["Adresse instruction","Valeur RAM","Stack","Flags"], a:0, e:"RIP pointe l'instruction courante."},
  {id:84, ch:6, q:"Little-endian signifie :", o:["Octet fort d'abord","Octet faible d'abord","Sans ordre","ASCII"], a:1, e:"x86_64 stocke l'octet faible en premier."},
  {id:85, ch:6, q:"Pour forcer la taille memoire :", o:["byte/word/dword/qword","movx","push","nop"], a:0, e:"NASM utilise byte/word/dword/qword."},

  // ===================== CHAPITRE 7 - NASM AVANCE (15) =====================
  {id:86, ch:7, q:"PUSH sur x86_64 :", o:["Augmente RSP","Diminue RSP de 8","Ne change rien","Met RAX a 0"], a:1, e:"PUSH reserve 8 octets."},
  {id:87, ch:7, q:"POP sur x86_64 :", o:["Diminue RSP","Augmente RSP de 8","Vide la RAM","Change RIP"], a:1, e:"POP restaure et remonte la pile."},
  {id:88, ch:7, q:"CALL fait :", o:["Saut simple","Pousse l'adresse retour","Vide la pile","Change RAX"], a:1, e:"CALL empile l'adresse retour."},
  {id:89, ch:7, q:"RET fait :", o:["Pop l'adresse retour","Ajoute 1","Reset","Active flags"], a:0, e:"RET recupere l'adresse retour."},
  {id:90, ch:7, q:"Alignement pile avant CALL :", o:["4 octets","8 octets","16 octets","32 octets"], a:2, e:"ABI x64 = alignement 16."},
  {id:91, ch:7, q:"Numero syscall exit (Linux) :", o:["1","2","60","80"], a:2, e:"exit = 60 en x86_64."},
  {id:92, ch:7, q:"Arguments syscall Linux 1..3 :", o:["RCX/RDX/R8","RDI/RSI/RDX","RAX/RBX/RCX","R8/R9/R10"], a:1, e:"RDI, RSI, RDX."},
  {id:93, ch:7, q:"Retour d'un syscall :", o:["RAX","RDI","RSP","RBP"], a:0, e:"RAX contient le resultat."},
  {id:94, ch:7, q:"Assembler sous Windows :", o:["nasm -f elf64","nasm -f win64","nasm -f bin","nasm -f macho"], a:1, e:"Format win64 pour Windows."},
  {id:95, ch:7, q:"ABI Windows: premier argument :", o:["RDI","RCX","RDX","R8"], a:1, e:"Win64 utilise RCX pour arg1."},
  {id:96, ch:7, q:"Linkage Windows avec MinGW :", o:["gcc prog.obj","ld prog.obj","avr-gcc","javac"], a:0, e:"GCC (MinGW) fait le linkage."},
  {id:97, ch:7, q:"Erreur MOV rax 5 :", o:["Virgule manquante","Mauvais registre","Pas d'ALU","Format ELF"], a:0, e:"Virgule obligatoire en NASM."},
  {id:98, ch:7, q:"Erreur MOV vs LEA typique :", o:["Utiliser MOV au lieu de LEA pour une adresse","Oublier un label","Changer RSP","Oublier .text"], a:0, e:"MOV dereference, LEA calcule une adresse."},
  {id:99, ch:7, q:"La pile x86_64 est :", o:["En RAM","En Flash","Dans le cache uniquement","Sur disque"], a:0, e:"La pile est en RAM."},
  {id:100, ch:7, q:"Syscall vs bibliotheque :", o:["Syscall = noyau, lib = wrapper","Identiques","Lib plus bas niveau","Syscall plus lent car RAM"], a:0, e:"Le syscall passe au noyau, la lib est un wrapper."}
];
