const ASM_QUESTIONS = [
  // ===================== CHAPITRE 1 - NUMERATION & LOGIQUE (15) =====================
  {id:1, ch:1, q:"Quelle base utilise le binaire ?", o:["2","8","10","16"], a:0, e:"Le binaire est en base 2."},
  {id:2, ch:1, q:"L'hexadecimal utilise :", o:["0-7","0-9","0-9 et A-F","A-Z"], a:2, e:"Hexa = 0-9 et A-F."},
  {id:3, ch:1, q:"1001b vaut en decimal :", o:["7","8","9","10"], a:2, e:"1*8 + 0*4 + 0*2 + 1*1 = 9."},
  {id:4, ch:1, q:"25 decimal vaut en binaire :", o:["11001","11100","10011","10110"], a:0, e:"25 = 16 + 8 + 1 = 11001."},
  {id:5, ch:1, q:"Complement a 2 signifie :", o:["Inverser les bits","Inverser puis +1","Ajouter 2","Multiplier par -1"], a:1, e:"Complement a 2 = inversion + 1."},
  {id:6, ch:1, q:"Sur 8 bits, -1 est :", o:["00000001","10000001","11111111","01111111"], a:2, e:"-1 = 0xFF en complement a 2."},
  {id:7, ch:1, q:"1010 AND 1100 =", o:["1110","1000","0100","0011"], a:1, e:"AND conserve les bits a 1 communs."},
  {id:8, ch:1, q:"1010 OR 0101 =", o:["1000","1111","0010","0101"], a:1, e:"OR force les bits a 1."},
  {id:9, ch:1, q:"1001 XOR 1010 =", o:["0011","1111","0001","0100"], a:0, e:"XOR = 1 quand les bits sont differents."},
  {id:10, ch:1, q:"La base octale utilise :", o:["0-7","0-9","A-F","0-1"], a:0, e:"Octal = base 8."},
  {id:11, ch:1, q:"Le bit de signe est :", o:["Le bit de poids faible","Le bit de poids fort","Le bit du milieu","Toujours 0"], a:1, e:"MSB = bit de signe."},
  {id:12, ch:1, q:"Sur 8 bits signes, la plage est :", o:["-127 a 128","-128 a 127","0 a 255","-255 a 255"], a:1, e:"Complement a 2: -128 a 127."},
  {id:13, ch:1, q:"Un decalage gauche par 1 equivaut a :", o:["Diviser par 2","Multiplier par 2","Ajouter 1","Inverser"], a:1, e:"Shift left = *2 (sans depassement)."},
  {id:14, ch:1, q:"Un decalage droite arithmetique :", o:["Remplit avec 0","Remplit avec le bit de signe","Inverse tous les bits","Ajoute 1"], a:1, e:"Il preserve le signe."},
  {id:15, ch:1, q:"Pour remettre un bit a 0 on fait :", o:["OR avec 1","AND avec un masque 0","XOR avec 1","ADD 1"], a:1, e:"AND avec un masque ou le bit est 0."},

  // ===================== CHAPITRE 2 - CPU & CYCLE (15) =====================
  {id:16, ch:2, q:"Ordre du cycle d'instruction :", o:["Decode-Fetch-Execute","Fetch-Decode-Execute","Execute-Decode-Fetch","Fetch-Execute-Decode"], a:1, e:"Cycle classique: fetch, decode, execute."},
  {id:17, ch:2, q:"L'ALU sert a :", o:["Stocker des donnees","Executer des operations","Gerer le bus","Synchroniser l'horloge"], a:1, e:"ALU = arithmetique et logique."},
  {id:18, ch:2, q:"Un registre est :", o:["Une memoire lente","Un stockage tres rapide","Un disque","Un bus"], a:1, e:"Les registres sont internes au CPU."},
  {id:19, ch:2, q:"Le bus d'adresses transporte :", o:["Les donnees","Les adresses memoire","Les flags","Le code source"], a:1, e:"Il indique ou lire/ecrire."},
  {id:20, ch:2, q:"Le cache est :", o:["Plus lent que la RAM","Plus rapide que la RAM","Un disque","Un bus"], a:1, e:"Le cache est plus rapide que la RAM."},
  {id:21, ch:2, q:"Le pointeur d'instruction x64 est :", o:["RSP","RIP","RAX","RDI"], a:1, e:"RIP pointe l'instruction en cours."},
  {id:22, ch:2, q:"Zero flag est a 1 quand :", o:["Resultat nul","Resultat negatif","Carry actif","Overflow actif"], a:0, e:"Z = 1 si resultat = 0."},
  {id:23, ch:2, q:"Carry flag indique :", o:["Overflow non signe","Overflow signe","Erreur memoire","Cache plein"], a:0, e:"Carry = depassement en non signe."},
  {id:24, ch:2, q:"Une interruption :", o:["Arrete le CPU","Suspend le cycle pour traiter un evenement","Efface la RAM","Change l'horloge"], a:1, e:"Le CPU traite un evenement prioritaire."},
  {id:25, ch:2, q:"Opcode signifie :", o:["Valeur des donnees","Code d'operation","Adresse RAM","Nom de variable"], a:1, e:"L'opcode est le code de l'instruction."},
  {id:26, ch:2, q:"L'architecture AVR est :", o:["Von Neumann","Harvard","RISC 16","CISC 32"], a:1, e:"AVR = Harvard (separation code/donnees)."},
  {id:27, ch:2, q:"La Flash contient :", o:["Des variables temporaires","Le programme","La pile","Les logs"], a:1, e:"Flash = memoire programme."},
  {id:28, ch:2, q:"La SRAM sert a :", o:["Stocker le programme","Stocker variables et pile","Stocker le BIOS","Acceder au bus"], a:1, e:"SRAM = variables et stack."},
  {id:29, ch:2, q:"Une machine a etats decrit :", o:["Un disque","Un enchainement d'etats","Une base de donnees","Un socket"], a:1, e:"Le CPU passe par des etats fixes."},
  {id:30, ch:2, q:"Hierarchie memoire du plus rapide au plus lent :", o:["RAM-Cache-Registres-Disque","Registres-Cache-RAM-Disque","Cache-RAM-Registres-Disque","Registres-RAM-Cache-Disque"], a:1, e:"Registres > cache > RAM > disque."},

  // ===================== CHAPITRE 3 - AVR & ATmega (15) =====================
  {id:31, ch:3, q:"Un microcontroleur integre :", o:["CPU seulement","CPU + memoire + peripheriques","RAM seulement","GPU"], a:1, e:"Microcontroleur = tout en un."},
  {id:32, ch:3, q:"ATmega328P contient :", o:["Flash, SRAM, EEPROM","GPU, VRAM","SSD","NIC"], a:0, e:"Les trois types de memoire sont presents."},
  {id:33, ch:3, q:"EEPROM est :", o:["Volatile","Non volatile","Toujours vide","Uniquement pour le code"], a:1, e:"EEPROM conserve les donnees apres extinction."},
  {id:34, ch:3, q:"DDR sert a :", o:["Definir entree/sortie","Activer un timer","Reset","Mesurer la tension"], a:0, e:"DDR fixe la direction des broches."},
  {id:35, ch:3, q:"PORT en mode entree permet :", o:["Activer un pull-up","Modifier la Flash","Reset","Changer l'horloge"], a:0, e:"PORT=1 active un pull-up."},
  {id:36, ch:3, q:"Un timer sert a :", o:["Compter le temps","Stocker un fichier","Activer un bus","Changer le CPU"], a:0, e:"Le timer mesure le temps et declenche des interruptions."},
  {id:37, ch:3, q:"La table des vecteurs d'interruptions :", o:["Liste les fonctions","Contient les adresses des ISR","Stocke la RAM","Change le clock"], a:1, e:"Chaque interruption a une adresse."},
  {id:38, ch:3, q:"Augmenter la frequence d'horloge :", o:["Rend plus lent","Accroit la consommation","Supprime la RAM","Coupe les ports"], a:1, e:"Plus de MHz = plus de consommation."},
  {id:39, ch:3, q:"UART est un bus :", o:["Serie","Parallele","Optique","I2C uniquement"], a:0, e:"UART est un protocole serie."},
  {id:40, ch:3, q:"ADC sert a :", o:["Convertir analogique en numerique","Compter des interruptions","Stocker des instructions","Mesurer des bits"], a:0, e:"ADC = Analog to Digital Converter."},
  {id:41, ch:3, q:"Microprocesseur vs microcontroleur :", o:["CPU seul vs CPU+periph","Identiques","RAM vs Flash","RISC vs CISC"], a:0, e:"Le microcontroleur integre des peripheriques."},
  {id:42, ch:3, q:"Registres generaux AVR :", o:["16","32","8","64"], a:1, e:"R0 a R31 = 32 registres."},
  {id:43, ch:3, q:"PORTB/PORTC/PORTD sont :", o:["Des ports E/S","Des timers","Des bus externes","Des interruptions"], a:0, e:"Ports E/S classiques sur ATmega."},
  {id:44, ch:3, q:"Le reset sert a :", o:["Eteindre definitivement","Revenir a l'etat initial","Effacer la Flash","Changer la tension"], a:1, e:"Reset remet l'etat par defaut."},
  {id:45, ch:3, q:"La Flash stocke :", o:["Variables temporaires","Programme","Logs","Pile"], a:1, e:"La Flash contient le code."},

  // ===================== CHAPITRE 4 - TOOLCHAIN (10) =====================
  {id:46, ch:4, q:"Compilation croisee =", o:["Compiler et executer sur PC","Compiler pour une autre cible","Compiler en binaire","Compiler sans outil"], a:1, e:"On compile pour une cible differente."},
  {id:47, ch:4, q:"avr-gcc est :", o:["Un editeur","Un compilateur","Un flash tool","Un IDE"], a:1, e:"avr-gcc compile pour AVR."},
  {id:48, ch:4, q:"Le fichier .elf est :", o:["Un binaire lie","Un fichier texte","Un fichier image","Un fichier audio"], a:0, e:".elf est le binaire genere."},
  {id:49, ch:4, q:"Le fichier .hex sert a :", o:["Stocker des photos","Programmer la Flash","Changer la RAM","Decrire les ports"], a:1, e:".hex est flashe sur la carte."},
  {id:50, ch:4, q:"AVRDude permet :", o:["Compiler","Flasher","Editer","Emuler"], a:1, e:"AVRDude charge le firmware."},
  {id:51, ch:4, q:"LED blink: DDR doit etre :", o:["0","1","Inchange","Negatif"], a:1, e:"DDR=1 configure la sortie."},
  {id:52, ch:4, q:"Si DDR bit = 0 alors la broche est :", o:["Sortie","Entree","Horloge","UART"], a:1, e:"DDR=0 = entree."},
  {id:53, ch:4, q:"Ordre logique: ", o:["flash -> compile -> hex","compile -> link -> hex -> flash","hex -> compile -> flash","link -> flash -> compile"], a:1, e:"Compilation, linkage, hex, flash."},
  {id:54, ch:4, q:"Pour flasher on specifie :", o:["Le port COM","La taille ecran","Le BIOS","Le GPU"], a:0, e:"AVRDude utilise le port serie/USB."},
  {id:55, ch:4, q:"Extension de l'objet :", o:[".o", ".hex", ".map", ".txt"], a:0, e:"Un objet est un .o."},

  // ===================== CHAPITRE 5 - AVR ASM (15) =====================
  {id:56, ch:5, q:"LDI charge :", o:["Une adresse","Une valeur immediate","Un flag","Un port"], a:1, e:"LDI charge une constante."},
  {id:57, ch:5, q:"MOV effectue :", o:["Un saut","Une copie de registre","Une addition","Un reset"], a:1, e:"MOV copie un registre."},
  {id:58, ch:5, q:"LDS sert a :", o:["Lire en SRAM","Ecrire en SRAM","Activer un port","Arreter"], a:0, e:"LDS lit une adresse memoire."},
  {id:59, ch:5, q:"STS sert a :", o:["Lire en SRAM","Ecrire en SRAM","Sauter","Tester Z"], a:1, e:"STS ecrit en SRAM."},
  {id:60, ch:5, q:"IN lit :", o:["Un registre E/S","La pile","La Flash","Une immediate"], a:0, e:"IN lit un registre d'E/S."},
  {id:61, ch:5, q:"OUT ecrit :", o:["Un registre E/S","La RAM","La Flash","Le stack"], a:0, e:"OUT ecrit vers un registre d'E/S."},
  {id:62, ch:5, q:"RJMP est :", o:["Un saut relatif","Un saut absolu","Un appel","Un test"], a:0, e:"RJMP saute relativement."},
  {id:63, ch:5, q:"BRNE saute si :", o:["Z=1","Z=0","C=1","O=1"], a:1, e:"BRNE = not equal (Z=0)."},
  {id:64, ch:5, q:"SREG contient :", o:["La pile","Les flags","Le programme","Les ports"], a:1, e:"SREG = status register."},
  {id:65, ch:5, q:"Le pointeur X est :", o:["R27:R26","R31:R30","R29:R28","R25:R24"], a:0, e:"X = R27:R26."},
  {id:66, ch:5, q:"Le pointeur Z est :", o:["R31:R30","R29:R28","R27:R26","R25:R24"], a:0, e:"Z = R31:R30."},
  {id:67, ch:5, q:"La pile AVR :", o:["Montee", "Descend (SP diminue)","Inchange","Est en Flash"], a:1, e:"SP diminue quand on push."},
  {id:68, ch:5, q:"CLR fait :", o:["Met a zero", "Met a 1", "Compare", "Saut"], a:0, e:"CLR met le registre a 0."},
  {id:69, ch:5, q:"SEI sert a :", o:["Desactiver IRQ","Activer IRQ","Reset","NOP"], a:1, e:"SEI active les interruptions."},
  {id:70, ch:5, q:"NOP signifie :", o:["Arret", "Pas d'operation", "Retour", "Charge"], a:1, e:"NOP ne fait rien."},

  // ===================== CHAPITRE 6 - NASM BASES (15) =====================
  {id:71, ch:6, q:"Section .data =", o:["Code", "Donnees initialisees", "Donnees non init", "Pile"], a:1, e:".data contient des donnees initialisees."},
  {id:72, ch:6, q:"Section .bss =", o:["Code", "Donnees initialisees", "Donnees non initialisees", "Flags"], a:2, e:".bss reserve la memoire."},
  {id:73, ch:6, q:"Section .text =", o:["Code", "RAM", "Cache", "Ports"], a:0, e:".text contient les instructions."},
  {id:74, ch:6, q:"RAX est :", o:["16 bits", "32 bits", "64 bits", "8 bits"], a:2, e:"RAX est 64 bits."},
  {id:75, ch:6, q:"EAX est :", o:["Le bas 32 bits de RAX", "Le haut 32 bits", "Un registre AVR", "Une adresse"], a:0, e:"EAX = partie 32 bits de RAX."},
  {id:76, ch:6, q:"MOV charge :", o:["Une adresse", "Une valeur", "Un saut", "Un flag"], a:1, e:"MOV copie une valeur."},
  {id:77, ch:6, q:"LEA charge :", o:["Une valeur", "Une adresse calculee", "Un port", "Un flag"], a:1, e:"LEA calcule une adresse."},
  {id:78, ch:6, q:"[rbx] signifie :", o:["Valeur immediate", "Adresse memoire", "Label", "Opcode"], a:1, e:"Crochets = dereferencement memoire."},
  {id:79, ch:6, q:"Un immediate s'ecrit :", o:["[5]", "5", "{5}", "(5)"], a:1, e:"Un immediate est une valeur directe."},
  {id:80, ch:6, q:"Adressage base+index*scale :", o:["[rbx+rcx*4]", "[rbx-]", "[rip]", "[rax+rax]"], a:0, e:"Index * scale est possible en x86_64."},
  {id:81, ch:6, q:"RSP est :", o:["Stack pointer", "Instruction pointer", "Data pointer", "Flag"], a:0, e:"RSP pointe la pile."},
  {id:82, ch:6, q:"RBP est souvent :", o:["Base pointer", "Port register", "Timer", "System call"], a:0, e:"RBP est la base du stack frame."},
  {id:83, ch:6, q:"RSI/RDI servent souvent a :", o:["Parametres source/dest", "Flags", "Timers", "Pile"], a:0, e:"RSI/RDI sont utilises pour source/destination."},
  {id:84, ch:6, q:"RIP contient :", o:["Adresse instruction", "Valeur RAM", "Stack", "Flags"], a:0, e:"RIP pointe l'instruction courante."},
  {id:85, ch:6, q:"LEA peut servir a :", o:["Addition simple", "Division", "System call", "Reset"], a:0, e:"LEA est utile pour faire des calculs d'adresse."},

  // ===================== CHAPITRE 7 - NASM AVANCE (15) =====================
  {id:86, ch:7, q:"PUSH sur x86_64 :", o:["Augmente RSP", "Diminue RSP de 8", "Ne change rien", "Met RAX a 0"], a:1, e:"PUSH reserve 8 octets."},
  {id:87, ch:7, q:"POP sur x86_64 :", o:["Diminue RSP", "Augmente RSP de 8", "Vide la RAM", "Change RIP"], a:1, e:"POP restaure et remonte la pile."},
  {id:88, ch:7, q:"Numero de syscall exit (Linux) :", o:["1", "2", "60", "80"], a:2, e:"exit = 60 en x86_64."},
  {id:89, ch:7, q:"Arg1 d'un syscall Linux passe par :", o:["RDI", "RSI", "RDX", "RCX"], a:0, e:"RDI = premier argument."},
  {id:90, ch:7, q:"Le retour d'un syscall est dans :", o:["RAX", "RDI", "RSP", "RBP"], a:0, e:"RAX contient le resultat."},
  {id:91, ch:7, q:"Assembler sous Windows :", o:["nasm -f elf64", "nasm -f win64", "nasm -f bin", "nasm -f macho"], a:1, e:"Format win64 pour Windows."},
  {id:92, ch:7, q:"Lier un objet NASM sur Windows :", o:["gcc prog.obj", "ld prog.o", "avr-gcc", "link.exe uniquement"], a:0, e:"GCC (MinGW) fait le linkage."},
  {id:93, ch:7, q:"RIP sert a :", o:["Pointer la pile", "Pointer l'instruction", "Stocker une constante", "Gerer la RAM"], a:1, e:"RIP = instruction pointer."},
  {id:94, ch:7, q:"Syntaxe correcte NASM :", o:["mov rax 5", "mov, rax, 5", "mov rax, 5", "mov = rax 5"], a:2, e:"Virgule obligatoire entre operandes."},
  {id:95, ch:7, q:"CALL fait :", o:["Saut simple", "Pousse l'adresse retour", "Vide la pile", "Change RAX"], a:1, e:"CALL empile l'adresse retour."},
  {id:96, ch:7, q:"RET fait :", o:["Pop l'adresse retour", "Ajoute 1", "Reset", "Active flags"], a:0, e:"RET recupere l'adresse retour."},
  {id:97, ch:7, q:"La pile x86_64 est :", o:["En RAM", "En Flash", "Dans le cache uniquement", "Sur disque"], a:0, e:"La pile est en RAM."},
  {id:98, ch:7, q:"MOV vs LEA erreur typique :", o:["Utiliser MOV au lieu de LEA pour une adresse", "Oublier un label", "Utiliser RAX", "Changer RSP"], a:0, e:"MOV dereference, LEA calcule une adresse."},
  {id:99, ch:7, q:"RSP doit etre aligne avant un call (ABI) :", o:["A 16 octets", "A 2 octets", "A 4 octets", "A 64 octets"], a:0, e:"Alignement 16 octets pour l'ABI."},
  {id:100, ch:7, q:"Syscall vs bibliotheque :", o:["Syscall = noyau, bibliotheque = wrapper", "Identiques", "Bibliotheque plus bas niveau", "Syscall plus lent car en RAM"], a:0, e:"Le syscall passe au noyau, la lib est un wrapper."}
];
