const CYB_QUESTIONS = [
  // ===================== CHAPITRE 1 - FONDATIONS (12) =====================
  {id:1, ch:1, q:"CIA signifie :", o:["Confidentialite, Integrite, Disponibilite","Controle, Inspection, Audit","Chiffrement, Identite, Autorisation","Cache, Instruction, Adresse"], a:0, e:"CIA = Confidentialite, Integrite, Disponibilite."},
  {id:2, ch:1, q:"Confidentialite signifie :", o:["Service accessible","Donnees accessibles uniquement aux autorises","Donnees non modifiees","Donnees publiques"], a:1, e:"Confidentialite = acces limite."},
  {id:3, ch:1, q:"Integrite signifie :", o:["Donnees non modifiees","Service arrete","Donnees publiques","Serveur lent"], a:0, e:"Integrite = absence de modification non autorisee."},
  {id:4, ch:1, q:"Disponibilite signifie :", o:["Donnees cachees","Service accessible","Donnees chiffrees","Ports fermes"], a:1, e:"Disponibilite = acces au service."},
  {id:5, ch:1, q:"Un actif est :", o:["Un danger","Quelque chose a proteger","Une attaque","Un malware"], a:1, e:"Actif = donnees, systemes, reseau, reputation."},
  {id:6, ch:1, q:"Une menace est :", o:["Un controle","Un danger potentiel","Un backup","Un outil de scan"], a:1, e:"Menace = danger potentiel."},
  {id:7, ch:1, q:"Une vulnerabilite est :", o:["Un correctif","Une faiblesse","Un mot de passe","Une cle"], a:1, e:"Vulnerabilite = faiblesse exploitable."},
  {id:8, ch:1, q:"Menace vs attaque :", o:["Identiques","Menace = potentiel, attaque = action","Attaque = outil","Menace = backup"], a:1, e:"La menace est potentielle, l'attaque est l'action."},
  {id:9, ch:1, q:"Risque =", o:["Menace + impact","Menace x vuln x impact","Vuln + backup","Chiffrement + firewall"], a:1, e:"Formule simple: menace x vuln x impact."},
  {id:10, ch:1, q:"Un controle de prevention sert a :", o:["Bloquer l'incident","Mesurer l'impact","Ecrire un rapport","Ignorer l'alerte"], a:0, e:"Prevention = eviter l'incident."},
  {id:11, ch:1, q:"Un controle de detection sert a :", o:["Detecter un incident","Empêcher un incident","Chiffrer","Sauvegarder"], a:0, e:"Detection = savoir qu'il se passe quelque chose."},
  {id:12, ch:1, q:"Un controle de reaction sert a :", o:["Limiter l'impact","Creer le risque","Supprimer les logs","Ouvrir tous les ports"], a:0, e:"Reaction = limiter les consequences."},

  // ===================== CHAPITRE 2 - MENACES (12) =====================
  {id:13, ch:2, q:"Un ransomware :", o:["Chiffre et demande une rancon","Supprime la RAM","Corrige un bug","Bloque le Wi-Fi"], a:0, e:"Ransomware = chiffrement + rancon."},
  {id:14, ch:2, q:"Un ver (worm) :", o:["S'attache a un fichier","Se propage seul","Est un firewall","Est un backup"], a:1, e:"Le ver se propage de lui-meme."},
  {id:15, ch:2, q:"Un trojan est :", o:["Un logiciel cache","Un protocole","Un routeur","Un patch"], a:0, e:"Trojan = se cache dans un logiciel legitime."},
  {id:16, ch:2, q:"Un spyware :", o:["Espionne l'utilisateur","Supprime les logs","Crache la RAM","Augmente la vitesse"], a:0, e:"Spyware collecte des infos en secret."},
  {id:17, ch:2, q:"Un keylogger :", o:["Enregistre les frappes clavier","Chiffre les fichiers","Ouvre les ports","Fait un backup"], a:0, e:"Keylogger capture les touches."},
  {id:18, ch:2, q:"Un botnet est :", o:["Un reseau de machines infectees","Un antivirus","Un pare-feu","Un OS"], a:0, e:"Botnet = machines controlees a distance."},
  {id:19, ch:2, q:"Le phishing vise a :", o:["Voler des identifiants","Crypter un disque","Ameliorer un reseau","Sauvegarder"], a:0, e:"Phishing = vol d'identifiants."},
  {id:20, ch:2, q:"Le spear phishing est :", o:["Un phishing cible","Un scan reseau","Un malware local","Un firewall"], a:0, e:"Spear phishing cible une personne precise."},
  {id:21, ch:2, q:"Ingenierie sociale =", o:["Manipuler l'humain","Scanner des ports","Creer un VLAN","Chiffrer"], a:0, e:"On exploite l'humain plutot que la technique."},
  {id:22, ch:2, q:"Une attaque DDoS provoque :", o:["Indisponibilite","Chiffrement","Vol d'identite","Compression"], a:0, e:"DDoS sature un service."},
  {id:23, ch:2, q:"Un type de DDoS est :", o:["Volumetrique","SQL","Hash","VPN"], a:0, e:"DDoS volumetrique sature la bande passante."},
  {id:24, ch:2, q:"Un signe de phishing :", o:["Urgence + lien suspect","Backup","VLAN","Antivirus"], a:0, e:"Urgence et lien suspect sont typiques."},

  // ===================== CHAPITRE 3 - RESEAU (12) =====================
  {id:25, ch:3, q:"Un pare-feu sert a :", o:["Filtrer le trafic","Chiffrer","Compiler","Executer"], a:0, e:"Pare-feu = filtrage du trafic."},
  {id:26, ch:3, q:"Un firewall stateful :", o:["Suit l'etat des connexions","Ignore le trafic","Chiffre","Supprime les logs"], a:0, e:"Stateful suit les connexions."},
  {id:27, ch:3, q:"NGFW ajoute :", o:["Inspection applicative","Moins de regles","Pas de logs","Pas de ports"], a:0, e:"NGFW apporte de la couche 7."},
  {id:28, ch:3, q:"Un critere de filtrage est :", o:["Adresse IP","Couleur du PC","Nom du clavier","Version du navigateur"], a:0, e:"Filtrage par IP/port/protocole."},
  {id:29, ch:3, q:"" + '"' + "deny by default" + '"' + " signifie :", o:["Tout autoriser","Tout refuser sauf le necessaire","Ouvrir tous les ports","Desactiver le firewall"], a:1, e:"On autorise seulement le necessaire."},
  {id:30, ch:3, q:"La segmentation sert a :", o:["Limiter la propagation","Accroitre la RAM","Supprimer les logs","Ouvrir tous les ports"], a:0, e:"Segmentation isole les zones."},
  {id:31, ch:3, q:"La DMZ est :", o:["Zone exposee controlee","Zone de RAM","Zone cache","Zone USB"], a:0, e:"DMZ isole les services publics."},
  {id:32, ch:3, q:"Un WAF protege :", o:["Applications web","Disques","BIOS","Clavier"], a:0, e:"WAF = Web Application Firewall."},
  {id:33, ch:3, q:"Le port 80 est :", o:["HTTP","SSH","DNS","SMTP"], a:0, e:"Port 80 = HTTP."},
  {id:34, ch:3, q:"Le port 443 est :", o:["HTTPS","FTP","DNS","RDP"], a:0, e:"Port 443 = HTTPS."},
  {id:35, ch:3, q:"Moindre privilege =", o:["Acces minimal","Tout autoriser","Admin partout","Ports ouverts"], a:0, e:"On donne le strict necessaire."},
  {id:36, ch:3, q:"Une regle any-any allow est :", o:["Risque majeur","Bonne pratique","Mitigation","IDS"], a:0, e:"Elle annule la securite du filtrage."},

  // ===================== CHAPITRE 4 - CRYPTO (12) =====================
  {id:37, ch:4, q:"Le chiffrement symetrique utilise :", o:["Deux cles","Une cle","Zero cle","Trois cles"], a:1, e:"Symetrique = une cle."},
  {id:38, ch:4, q:"Un exemple symetrique :", o:["RSA","AES","DSA","ECC"], a:1, e:"AES est symetrique."},
  {id:39, ch:4, q:"Un exemple asymetrique :", o:["AES","RSA","ChaCha20","MD5"], a:1, e:"RSA est asymetrique."},
  {id:40, ch:4, q:"Une cle publique sert a :", o:["Chiffrer","Dechiffrer","Stocker","Compresser"], a:0, e:"On chiffre avec la cle publique."},
  {id:41, ch:4, q:"Le hash sert a :", o:["Integrite","Chiffrement","Sauvegarde","Routing"], a:0, e:"Hash = integrite."},
  {id:42, ch:4, q:"Une signature numerique prouve :", o:["L'auteur","Le debit","La vitesse","Le port"], a:0, e:"Signature = auteur + integrite."},
  {id:43, ch:4, q:"TLS combine :", o:["Asymetrique + symetrique","Symetrique seul","Hash seul","Sans cle"], a:0, e:"TLS negocie une cle symetrique."},
  {id:44, ch:4, q:"Un salt est :", o:["Un sel ajoute au hash","Un port","Un virus","Un firewall"], a:0, e:"Salt renforce le hash des mots de passe."},
  {id:45, ch:4, q:"Un hash est :", o:["A sens unique","Reversible","Un chiffrement","Un certificat"], a:0, e:"Un hash n'est pas reversible."},
  {id:46, ch:4, q:"Une cle privee doit etre :", o:["Publique","Secrete","Supprimee","Partagee"], a:1, e:"La cle privee doit rester secrete."},
  {id:47, ch:4, q:"Le chiffrement symetrique est :", o:["Rapide","Tres lent","Inutile","Sans cle"], a:0, e:"Le symetrique est rapide."},
  {id:48, ch:4, q:"L'asymetrique sert surtout a :", o:["Echange de cles","Chiffrer gros volumes","Compresser","Router"], a:0, e:"Il sert a l'echange et aux signatures."},

  // ===================== CHAPITRE 5 - CRC (13) =====================
  {id:49, ch:5, q:"CRC signifie :", o:["Cyclic Redundancy Check","Critical Risk Control","Crypto Random Code","Central Routing Core"], a:0, e:"CRC = Cyclic Redundancy Check."},
  {id:50, ch:5, q:"Le CRC sert a :", o:["Detecter des erreurs","Chiffrer","Compresser","Sauvegarder"], a:0, e:"CRC detecte les erreurs de transmission."},
  {id:51, ch:5, q:"Le CRC est :", o:["Le quotient","Le reste","Le produit","La somme"], a:1, e:"CRC = reste de la division polynomiale."},
  {id:52, ch:5, q:"La division CRC se fait :", o:["Mod 2 (XOR)","Mod 10","En decimal","Avec des virgules"], a:0, e:"Division polynomiale mod 2."},
  {id:53, ch:5, q:"Si degre de G(x) = k alors :", o:["CRC = k bits","CRC = 2k","CRC = message","CRC = 1 bit"], a:0, e:"Le CRC a k bits."},
  {id:54, ch:5, q:"Avant division, on :", o:["Ajoute k zeros","Supprime k bits","Change la base","Chiffre"], a:0, e:"On decale de k bits (x^k)."},
  {id:55, ch:5, q:"Message transmis =", o:["M seul","M + CRC","CRC seul","M - CRC"], a:1, e:"On concatene M et CRC."},
  {id:56, ch:5, q:"Si le reste est 0 au controle :", o:["Message correct","Message faux","Erreur certaine","Impossible"], a:0, e:"Reste nul = pas d'erreur detectee."},
  {id:57, ch:5, q:"CRC ne fait pas :", o:["Correction d'erreurs","Detection","Verification","Controle"], a:0, e:"CRC ne corrige pas les erreurs."},
  {id:58, ch:5, q:"G(x)=x^3+x+1 correspond aux bits :", o:["1011","1101","1110","1001"], a:0, e:"x^3 + x + 1 = 1 0 1 1."},
  {id:59, ch:5, q:"G(x)=x^4+x+1 correspond aux bits :", o:["10011","10110","11001","11100"], a:0, e:"x^4 + x + 1 = 10011."},
  {id:60, ch:5, q:"Le polynome generateur doit :", o:["Commencer par 1","Finir par 0","Etre pair","Etre negatif"], a:0, e:"Le bit de poids fort est 1."},
  {id:61, ch:5, q:"CRC detecte :", o:["Erreurs","Attaques","Spam","Virus"], a:0, e:"CRC detecte les erreurs de transmission."},

  // ===================== CHAPITRE 6 - NMAP (13) =====================
  {id:62, ch:6, q:"Nmap signifie :", o:["Network Mapper","Node Manager","Net Map Pro","Network Mail"], a:0, e:"Nmap = Network Mapper."},
  {id:63, ch:6, q:"Nmap sert a :", o:["Scanner un reseau","Chiffrer","Sauvegarder","Compiler"], a:0, e:"Nmap cartographie le reseau."},
  {id:64, ch:6, q:"-sS est :", o:["SYN scan","UDP scan","OS scan","FTP scan"], a:0, e:"-sS = SYN scan."},
  {id:65, ch:6, q:"-sT est :", o:["TCP connect","UDP scan","Ping","Traceroute"], a:0, e:"-sT = TCP connect."},
  {id:66, ch:6, q:"-sU sert a :", o:["Scan UDP","Scan HTTP","Scan OS","Scan ping"], a:0, e:"-sU pour UDP."},
  {id:67, ch:6, q:"-sV signifie :", o:["Version detection","Verbose","VPN","Visual"], a:0, e:"-sV detecte les versions."},
  {id:68, ch:6, q:"-O signifie :", o:["Detection OS","Output","Open","Order"], a:0, e:"-O tente d'identifier l'OS."},
  {id:69, ch:6, q:"-p 1-1000 :", o:["Ports 1 a 1000","IP 1 a 1000","Temps 1-1000","Threads"], a:0, e:"-p selectionne les ports."},
  {id:70, ch:6, q:"Un port open signifie :", o:["Service accessible","Port ferme","Filtre","Pas de reseau"], a:0, e:"Open = service repond."},
  {id:71, ch:6, q:"Un port filtered signifie :", o:["Pare-feu filtre","Service ok","DNS ok","OS connu"], a:0, e:"Filtered = pare-feu masque la reponse."},
  {id:72, ch:6, q:"-A active :", o:["Scan agressif","Scan lent","Scan local","Scan RAM"], a:0, e:"-A = version + OS + scripts."},
  {id:73, ch:6, q:"-Pn fait :", o:["Pas de ping","Ping rapide","Pas de ports","Pas de DNS"], a:0, e:"-Pn ignore le ping initial."},
  {id:74, ch:6, q:"Avant un scan il faut :", o:["Autorisation","Un VPN","Un antivirus","Un VLAN"], a:0, e:"Toujours obtenir une autorisation."},

  // ===================== CHAPITRE 7 - SNORT (13) =====================
  {id:75, ch:7, q:"Snort est :", o:["IDS/IPS","Firewall","OS","Scanner"], a:0, e:"Snort est un IDS/IPS open source."},
  {id:76, ch:7, q:"IDS signifie :", o:["Detection + alerte","Blocage","Chiffrement","Backup"], a:0, e:"IDS detecte et alerte."},
  {id:77, ch:7, q:"IPS signifie :", o:["Detection + blocage","Detection seule","Chiffrement","Backup"], a:0, e:"IPS bloque le trafic malveillant."},
  {id:78, ch:7, q:"Snort peut fonctionner en mode :", o:["Sniffer","Logger","IDS/IPS","Toutes"], a:3, e:"Snort a plusieurs modes."},
  {id:79, ch:7, q:"Une regle Snort commence par :", o:["msg","sid","action protocole","content"], a:2, e:"La regle commence par action + protocole."},
  {id:80, ch:7, q:"sid sert a :", o:["Identifiant de regle","Port","Adresse IP","Option HTTP"], a:0, e:"sid = identifiant unique."},
  {id:81, ch:7, q:"content sert a :", o:["Matcher une signature","Changer le port","Desactiver la regle","Afficher l'heure"], a:0, e:"content recherche une signature."},
  {id:82, ch:7, q:"Un preprocessor sert a :", o:["Normaliser le trafic","Changer les cles","Reset","Compresser"], a:0, e:"Preprocessor prepare le trafic."},
  {id:83, ch:7, q:"En mode IPS, Snort est :", o:["Inline","Passif","Off","Disque"], a:0, e:"IPS = inline pour bloquer."},
  {id:84, ch:7, q:"Un faux positif est :", o:["Alerte a tort","Aucune alerte","Bug OS","Virus"], a:0, e:"Faux positif = alerte incorrecte."},
  {id:85, ch:7, q:"Un faux negatif est :", o:["Attaque non detectee","Alerte en trop","Backup rate","Port ferme"], a:0, e:"Faux negatif = attaque ratee."},
  {id:86, ch:7, q:"Snort s'appuie sur :", o:["Des regles","Des certificats","Des VLAN","Des BIOS"], a:0, e:"Snort utilise des regles."},
  {id:87, ch:7, q:"Mode logger sert a :", o:["Enregistrer les paquets","Bloquer","Chiffrer","Compiler"], a:0, e:"Logger enregistre les paquets."},

  // ===================== CHAPITRE 8 - RISQUE & LEGAL (13) =====================
  {id:88, ch:8, q:"Premiere etape analyse de risque :", o:["Prioriser","Identifier les actifs","Transferer","Supprimer"], a:1, e:"On commence par identifier."},
  {id:89, ch:8, q:"Impact mesure :", o:["Gravite des consequences","Vitesse","Memoire","Port"], a:0, e:"Impact = gravite des consequences."},
  {id:90, ch:8, q:"Probabilite mesure :", o:["Chance de survenue","Taille RAM","CPU","Port"], a:0, e:"Probabilite = chance que cela arrive."},
  {id:91, ch:8, q:"Traiter un risque peut signifier :", o:["Eviter","Reduire","Transferer","Toutes"], a:3, e:"Les 3 options + accepter existent."},
  {id:92, ch:8, q:"Transferer un risque peut se faire par :", o:["Assurance","Cablage","RAM","BIOS"], a:0, e:"On peut transferer via assurance."},
  {id:93, ch:8, q:"Accepter un risque signifie :", o:["Le nier","Le garder si cout trop eleve","Le supprimer","Le chiffrer"], a:1, e:"Accepter = pas d'action supplementaire."},
  {id:94, ch:8, q:"Une intrusion non autorisee est :", o:["Legale","Un delit","Une pratique normale","Une sauvegarde"], a:1, e:"Intrusion = delit."},
  {id:95, ch:8, q:"Les donnees personnelles doivent etre :", o:["Protegees","Ignorees","Publiees","Supprimees"], a:0, e:"Elles doivent etre protegees."},
  {id:96, ch:8, q:"Une violation grave peut exiger :", o:["Un signalement","Une mise a jour","Un reboot","Un scan Nmap"], a:0, e:"Selon le contexte, une notification est requise."},
  {id:97, ch:8, q:"Former les employes sert a :", o:["Reduire les erreurs humaines","Augmenter la RAM","Bloquer le DNS","Compresser"], a:0, e:"L'humain est une cause majeure d'incident."},
  {id:98, ch:8, q:"Un plan de traitement doit :", o:["Prioriser les risques","Tout ignorer","Supprimer les logs","Tout ouvrir"], a:0, e:"On priorise les risques les plus critiques."},
  {id:99, ch:8, q:"Le risque eleve se traite :", o:["En priorite","En dernier","Jamais","Au hasard"], a:0, e:"On traite le plus critique en premier."},
  {id:100, ch:8, q:"L'analyse de risque doit etre :", o:["Un processus continu","Unique","Inutile","Secrete"], a:0, e:"Le contexte evolue, il faut reevaluer."}
];
